---
vagrantfile-local:
    vm:
        box: centos65
        box_url: 'http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-puppet.box'
        hostname: flows.dev
        network:
            private_network: 192.168.42.10
            forwarded_port:
                2CLixfTH8U77:
                    host: '8080'
                    guest: '80'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: "on"
                    memory: '512'
                    name: 'flows-box'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: 'puppet/manifests'
                manifest_file: 'base.pp'
                modules_path: 'puppet/modules'
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder: {  } # add extra folders here
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect